# Generated by Django 4.2.16 on 2024-10-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
