# Generated by Django 4.2.16 on 2024-10-11 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.AddField(
            model_name='favoritequestion',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favoritequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='quizhub.question'),
        ),
        migrations.AlterField(
            model_name='favoritequestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read', to='quizhub.question'),
        ),
        migrations.AlterField(
            model_name='readquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
